### ISSUE TITLE
SingleTrackFragment will ein Fragment inflaten

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#69]
Bei SingleTrackFragment bekommen ich die Exception:

```
07-01 18:09:41.662 3752-3752/? E/InputEventSender: Exception dispatching finished signal.
07-01 18:09:41.662 3752-3752/? E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
07-01 18:09:41.662 3752-3752/? E/MessageQueue-JNI: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class fragment
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                       at edu.hm.cs.bikebattle.app.fragments.single.SingleTrackFragment.onCreateView(SingleTrackFragment.java:74)
                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                       at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:975)
                                                       at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1670)
                                                       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:586)
                                                       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:189)
                                                       at edu.hm.cs.bikebattle.app.activities.MainActivity.onBackPressed(MainActivity.java:233)
```

Hier ist in der XML Datei ein Fragment eingebunden. Das kann so wohl nicht "inflatet werden"

**Comment by darenegade** [comment]
Passiert beim onBackPressed

**Comment by NeelzDev** [comment]
Selbes Problem habe ich, wenn ich eine Route auswähle, dann auf start und in der Tracking Activity den Floating Button anwähle.

**Comment by NeelzDev** [comment]
Leider noch keine Lösung aber ich arbeite dran.
